services:
    auto-movie-resources-manager:
        image: wuxin12/auto-movie-resources-manager:v1
        container_name: auto-movie-resources-manager
        labels:
            createdBy: Apps
        environment:
            - UID=0
            - GID=0
            - GIDLIST=0
            - LOG_LEVEL=debug
        network_mode: bridge
        ports:
            - "8092:8092"
            - "8090:8090"
        restart: always
        volumes:
            - /etc/hosts:/etc/hosts
            - /volume2/video:/app/video
            - ./config/config.yaml:/app/config/config.yaml
            - ./log:/app/log
            - ./nginx/log:/var/log/nginx
        working_dir: /app

    postgres:
      image: postgres:16-alpine
      environment:
        POSTGRES_DB: auto-movie-resources-manager
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: 123456
        UID: 0
        GID: 0
        GIDLIST: 0
      ports:
        - 5432:5432
      restart: always
      volumes:
        - ./postgresql:/var/lib/postgresql/data

    redis:
      image: redis:7.2-alpine
      restart: always
      ports:
        - 6479:6379
      volumes:
        - ./redis/data:/data
      environment:
        - UID=0
        - GID=0
        - GIDLIST=0

# 声明要使用的网络
networks:
  moontv_moontv-network:
    # 表示使用已存在的网络
    external: true
