version: '3.8'  # 指定compose版本，支持更多特性

services:
    auto-movie-resources-manager:
        image: wuxin12/auto-movie-resources-manager:v0.6
        container_name: auto-movie-resources-manager
        labels:
            createdBy: Apps
        ports:
            - "8092:8092"     # Emby端口，手机、web访问Emby使用
            - "8090:8090"     # 服务端口，配置到strm_url上面，需要注意如果需要外网访问，请配置公网到strm_url配置上面
        restart: unless-stopped  # 更合理的重启策略
        environment:
          - EMBY_HOST=http://xxx.xxx..xx:8096       # Emby地址，容器能访问的即可，无需公网,302代理使用
          - USERNAME = admin                        # 平台登录用户名，可选，默认admin
          - PASSWORD = 123456                       # 平台登录密码，可选，默认123456
        volumes:
            - ./postgres-data:/data/postgres                # 数据库持久化
            - ./config/config.yaml:/app/config/config.yaml   # 配置文件
            - /etc/hosts:/etc/hosts                         # 映射host，可选
            - /volume2/video:/app/video                     # 媒体库STRM映射目录
            - ./log:/app/log                                # 日志
        networks:
            - auto-movie-resources-manager

networks:
    auto-movie-resources-manager:
        name: auto-movie-resources-manager
        driver: bridge
